apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ include "service.namespace" . }}
  labels: 
    {{- include "service.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.serviceName | quote }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  RELEASE_VERSION: {{ .Values.releaseVersion | quote }}
  APP_PORT: {{ .Values.containerPort | quote }}
  {{- range .Values.secrets }}
  {{ .env }}: {{ printf "%s/%s" (include "service.secretsDir" $) .name | quote }}
  {{- end }}

