{{- if .Values.metrics }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ include "service.namespace" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
  targetLabels:
    fromPod:
      - from: app.kubernetes.io/version
        to: version
{{- end }}
