# Staging overrides, layered after values.yaml.
environment: staging

image:
  repository: us-east4-docker.pkg.dev/gke-build-proj/gke-build-proj-staging-images/platform-verification-api
  digest: "sha256:daba5ff446f0051d31c31e6ae29fcbcc8e5d70ae81b74e312a9612656378b7b0"
releaseVersion: "sha-d1b3f48"

secrets:
  - name: staging-platform-verification-api-demo
    env: SECRET_FILE

httpRoute:
  hostname: api.staging.gke.josephdara.com

metrics:
  port: 9090
