apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Service Applications deployed into the staging namespace
  sourceRepos:
    - https://github.com/Josephdara/gke-platform.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: staging
  namespaceResourceWhitelist:
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: secrets-store.csi.x-k8s.io
      kind: SecretProviderClass
