apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-controllers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  description: Platform controllers installed by Argo CD, currently Kyverno
  sourceRepos:
    - https://github.com/Josephdara/gke-platform.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kyverno
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
