apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "3"
    limits.memory: 2Gi
    pods: "10"
