apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-platform
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/Josephdara/gke-platform.git
    targetRevision: main
    path: platform/cluster
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
