apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Shared platform resources, synced from platform/cluster
  sourceRepos:
    - https://github.com/Josephdara/gke-platform.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: staging
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: policies.kyverno.io
      kind: ValidatingPolicy
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: AppProject
    - group: argoproj.io
      kind: Application
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: gateway.networking.k8s.io
      kind: Gateway
